library(glmnet)
#Read in file of features from Sanger study
mut<-read.csv("en_input_w5.csv")
# Read in SOCRATES list of GI50s/percentage growth inhibition
sensa<-read.csv("Everolimus.csv")
#Merge these two files together
names(mut)[names(mut)=="X"]<-"sample_name"
new<-merge(mut,sensa, by="sample_name")

x<-as.matrix(new[,2:13886])
y<-as.vector(new[,13887], mode="numeric")

#Perform elastic net analysis 100 times and save output of each run
for (i in 1:100){
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, paste('Everolimus', i, 'csv', sep = '.'))
}

#Read in output files
file1<-read.csv("Everolimus.1.csv")
file2<-read.csv("Everolimus.2.csv")
file3<-read.csv("Everolimus.3.csv")
file4<-read.csv("Everolimus.4.csv")
file5<-read.csv("Everolimus.5.csv")
file6<-read.csv("Everolimus.6.csv")
file7<-read.csv("Everolimus.7.csv")
file8<-read.csv("Everolimus.8.csv")
file9<-read.csv("Everolimus.9.csv")
file10<-read.csv("Everolimus.10.csv")
file11<-read.csv("Everolimus.11.csv")
file12<-read.csv("Everolimus.12.csv")
file13<-read.csv("Everolimus.13.csv")
file14<-read.csv("Everolimus.14.csv")
file15<-read.csv("Everolimus.15.csv")
file16<-read.csv("Everolimus.16.csv")
file17<-read.csv("Everolimus.17.csv")
file18<-read.csv("Everolimus.18.csv")
file19<-read.csv("Everolimus.19.csv")
file20<-read.csv("Everolimus.20.csv")
file21<-read.csv("Everolimus.21.csv")
file22<-read.csv("Everolimus.22.csv")
file23<-read.csv("Everolimus.23.csv")
file24<-read.csv("Everolimus.24.csv")
file25<-read.csv("Everolimus.25.csv")
file26<-read.csv("Everolimus.26.csv")
file27<-read.csv("Everolimus.27.csv")
file28<-read.csv("Everolimus.28.csv")
file29<-read.csv("Everolimus.29.csv")
file30<-read.csv("Everolimus.30.csv")
file31<-read.csv("Everolimus.31.csv")
file32<-read.csv("Everolimus.32.csv")
file33<-read.csv("Everolimus.33.csv")
file34<-read.csv("Everolimus.34.csv")
file35<-read.csv("Everolimus.35.csv")
file36<-read.csv("Everolimus.36.csv")
file37<-read.csv("Everolimus.37.csv")
file38<-read.csv("Everolimus.38.csv")
file39<-read.csv("Everolimus.39.csv")
file40<-read.csv("Everolimus.40.csv")
file41<-read.csv("Everolimus.41.csv")
file42<-read.csv("Everolimus.42.csv")
file43<-read.csv("Everolimus.43.csv")
file44<-read.csv("Everolimus.44.csv")
file45<-read.csv("Everolimus.45.csv")
file46<-read.csv("Everolimus.46.csv")
file47<-read.csv("Everolimus.47.csv")
file48<-read.csv("Everolimus.48.csv")
file49<-read.csv("Everolimus.49.csv")
file50<-read.csv("Everolimus.50.csv")
file51<-read.csv("Everolimus.51.csv")
file52<-read.csv("Everolimus.52.csv")
file53<-read.csv("Everolimus.53.csv")
file54<-read.csv("Everolimus.54.csv")
file55<-read.csv("Everolimus.55.csv")
file56<-read.csv("Everolimus.56.csv")
file57<-read.csv("Everolimus.57.csv")
file58<-read.csv("Everolimus.58.csv")
file59<-read.csv("Everolimus.59.csv")
file60<-read.csv("Everolimus.60.csv")
file61<-read.csv("Everolimus.61.csv")
file62<-read.csv("Everolimus.62.csv")
file63<-read.csv("Everolimus.63.csv")
file64<-read.csv("Everolimus.64.csv")
file65<-read.csv("Everolimus.65.csv")
file66<-read.csv("Everolimus.66.csv")
file67<-read.csv("Everolimus.67.csv")
file68<-read.csv("Everolimus.68.csv")
file69<-read.csv("Everolimus.69.csv")
file70<-read.csv("Everolimus.70.csv")
file71<-read.csv("Everolimus.71.csv")
file72<-read.csv("Everolimus.72.csv")
file73<-read.csv("Everolimus.73.csv")
file74<-read.csv("Everolimus.74.csv")
file75<-read.csv("Everolimus.75.csv")
file76<-read.csv("Everolimus.76.csv")
file77<-read.csv("Everolimus.77.csv")
file78<-read.csv("Everolimus.78.csv")
file79<-read.csv("Everolimus.79.csv")
file80<-read.csv("Everolimus.80.csv")
file81<-read.csv("Everolimus.81.csv")
file82<-read.csv("Everolimus.82.csv")
file83<-read.csv("Everolimus.83.csv")
file84<-read.csv("Everolimus.84.csv")
file85<-read.csv("Everolimus.85.csv")
file86<-read.csv("Everolimus.86.csv")
file87<-read.csv("Everolimus.87.csv")
file88<-read.csv("Everolimus.88.csv")
file89<-read.csv("Everolimus.89.csv")
file90<-read.csv("Everolimus.90.csv")
file91<-read.csv("Everolimus.91.csv")
file92<-read.csv("Everolimus.92.csv")
file93<-read.csv("Everolimus.93.csv")
file94<-read.csv("Everolimus.94.csv")
file95<-read.csv("Everolimus.95.csv")
file96<-read.csv("Everolimus.96.csv")
file97<-read.csv("Everolimus.97.csv")
file98<-read.csv("Everolimus.98.csv")
file99<-read.csv("Everolimus.99.csv")
file100<-read.csv("Everolimus.100.csv")

#Merge results from all runs into a single file
all<-merge(file1,file2, by="X")
all<-merge(all,file3, by="X")
all<-merge(all,file4, by="X")
all<-merge(all,file5, by="X")
all<-merge(all,file6, by="X")
all<-merge(all,file7, by="X")
all<-merge(all,file8, by="X")
all<-merge(all,file9, by="X")
all<-merge(all,file10, by="X")
all<-merge(all,file11, by="X")
all<-merge(all,file12, by="X")
all<-merge(all,file13, by="X")
all<-merge(all,file14, by="X")
all<-merge(all,file15, by="X")
all<-merge(all,file16, by="X")
all<-merge(all,file17, by="X")
all<-merge(all,file18, by="X")
all<-merge(all,file19, by="X")
all<-merge(all,file20, by="X")
all<-merge(all,file21, by="X")
all<-merge(all,file22, by="X")
all<-merge(all,file23, by="X")
all<-merge(all,file24, by="X")
all<-merge(all,file25, by="X")
all<-merge(all,file26, by="X")
all<-merge(all,file27, by="X")
all<-merge(all,file28, by="X")
all<-merge(all,file29, by="X")
all<-merge(all,file30, by="X")
all<-merge(all,file31, by="X")
all<-merge(all,file32, by="X")
all<-merge(all,file33, by="X")
all<-merge(all,file34, by="X")
all<-merge(all,file35, by="X")
all<-merge(all,file36, by="X")
all<-merge(all,file37, by="X")
all<-merge(all,file38, by="X")
all<-merge(all,file39, by="X")
all<-merge(all,file40, by="X")
all<-merge(all,file41, by="X")
all<-merge(all,file42, by="X")
all<-merge(all,file43, by="X")
all<-merge(all,file44, by="X")
all<-merge(all,file45, by="X")
all<-merge(all,file46, by="X")
all<-merge(all,file47, by="X")
all<-merge(all,file48, by="X")
all<-merge(all,file49, by="X")
all<-merge(all,file50, by="X")
all<-merge(all,file51, by="X")
all<-merge(all,file52, by="X")
all<-merge(all,file53, by="X")
all<-merge(all,file54, by="X")
all<-merge(all,file55, by="X")
all<-merge(all,file56, by="X")
all<-merge(all,file57, by="X")
all<-merge(all,file58, by="X")
all<-merge(all,file59, by="X")
all<-merge(all,file60, by="X")
all<-merge(all,file61, by="X")
all<-merge(all,file62, by="X")
all<-merge(all,file63, by="X")
all<-merge(all,file64, by="X")
all<-merge(all,file65, by="X")
all<-merge(all,file66, by="X")
all<-merge(all,file67, by="X")
all<-merge(all,file68, by="X")
all<-merge(all,file69, by="X")
all<-merge(all,file70, by="X")
all<-merge(all,file71, by="X")
all<-merge(all,file72, by="X")
all<-merge(all,file73, by="X")
all<-merge(all,file74, by="X")
all<-merge(all,file75, by="X")
all<-merge(all,file76, by="X")
all<-merge(all,file77, by="X")
all<-merge(all,file78, by="X")
all<-merge(all,file79, by="X")
all<-merge(all,file80, by="X")
all<-merge(all,file81, by="X")
all<-merge(all,file82, by="X")
all<-merge(all,file83, by="X")
all<-merge(all,file84, by="X")
all<-merge(all,file85, by="X")
all<-merge(all,file86, by="X")
all<-merge(all,file87, by="X")
all<-merge(all,file88, by="X")
all<-merge(all,file89, by="X")
all<-merge(all,file90, by="X")
all<-merge(all,file91, by="X")
all<-merge(all,file92, by="X")
all<-merge(all,file93, by="X")
all<-merge(all,file94, by="X")
all<-merge(all,file95, by="X")
all<-merge(all,file96, by="X")
all<-merge(all,file97, by="X")
all<-merge(all,file98, by="X")
all<-merge(all,file99, by="X")
all<-merge(all,file100, by="X")
#Write results as a single file
write.csv(all, "Everolimus.overall.csv")
