library(glmnet)
mut<-read.csv("en_input_w5.csv")
sensa<-read.csv("Everolimus.csv")
names(mut)[names(mut)=="X"]<-"sample_name"
new<-merge(mut,sensa, by="sample_name")

x<-as.matrix(new[,2:13886])
y<-as.vector(new[,13887], mode="numeric")


 cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
 b<-as.matrix(coef(cvfit, s="lambda.min"))
 write.csv(b, "Everolimus_Results_1.csv")
 cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
 b<-as.matrix(coef(cvfit, s="lambda.min"))
 write.csv(b, "Everolimus_Results_2.csv")
 cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
 b<-as.matrix(coef(cvfit, s="lambda.min"))
 write.csv(b, "Everolimus_Results_3.csv")
 cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
 b<-as.matrix(coef(cvfit, s="lambda.min"))
 write.csv(b, "Everolimus_Results_4.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_5.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_6.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_7.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_8.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_9.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_10.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_11.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_12.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_13.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_14.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_15.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_16.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_17.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_18.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_19.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_20.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_21.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_22.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_23.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_24.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_25.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_26.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_27.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_28.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_29.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_30.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_31.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_32.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_33.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_34.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_35.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_36.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_37.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_38.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_39.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_40.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_41.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_42.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_43.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_44.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_45.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_46.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_47.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_48.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_49.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_50.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_51.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_52.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_53.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_54.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_55.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_56.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_57.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_58.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_59.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_60.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_61.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_62.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_63.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_64.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_65.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_66.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_67.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_68.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_69.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_70.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_71.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_72.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_73.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_74.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_75.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_76.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_77.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_78.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_79.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_80.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_81.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_82.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_83.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_84.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_85.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_86.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_87.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_88.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_89.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_90.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_91.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_92.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_93.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_94.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_95.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_96.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_97.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_98.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_99.csv")
cvfit=cv.glmnet(x,y, family="gaussian", type.measure="class")
b<-as.matrix(coef(cvfit, s="lambda.min"))
write.csv(b, "Everolimus_Results_100.csv")

file1<-read.csv("Everolimus_Results_1.csv")
file2<-read.csv("Everolimus_Results_2.csv")
file3<-read.csv("Everolimus_Results_3.csv")
file4<-read.csv("Everolimus_Results_4.csv")
file5<-read.csv("Everolimus_Results_5.csv")
file6<-read.csv("Everolimus_Results_6.csv")
file7<-read.csv("Everolimus_Results_7.csv")
file8<-read.csv("Everolimus_Results_8.csv")
file9<-read.csv("Everolimus_Results_9.csv")
file10<-read.csv("Everolimus_Results_10.csv")
file11<-read.csv("Everolimus_Results_11.csv")
file12<-read.csv("Everolimus_Results_12.csv")
file13<-read.csv("Everolimus_Results_13.csv")
file14<-read.csv("Everolimus_Results_14.csv")
file15<-read.csv("Everolimus_Results_15.csv")
file16<-read.csv("Everolimus_Results_16.csv")
file17<-read.csv("Everolimus_Results_17.csv")
file18<-read.csv("Everolimus_Results_18.csv")
file19<-read.csv("Everolimus_Results_19.csv")
file20<-read.csv("Everolimus_Results_20.csv")
file21<-read.csv("Everolimus_Results_21.csv")
file22<-read.csv("Everolimus_Results_22.csv")
file23<-read.csv("Everolimus_Results_23.csv")
file24<-read.csv("Everolimus_Results_24.csv")
file25<-read.csv("Everolimus_Results_25.csv")
file26<-read.csv("Everolimus_Results_26.csv")
file27<-read.csv("Everolimus_Results_27.csv")
file28<-read.csv("Everolimus_Results_28.csv")
file29<-read.csv("Everolimus_Results_29.csv")
file30<-read.csv("Everolimus_Results_30.csv")
file31<-read.csv("Everolimus_Results_31.csv")
file32<-read.csv("Everolimus_Results_32.csv")
file33<-read.csv("Everolimus_Results_33.csv")
file34<-read.csv("Everolimus_Results_34.csv")
file35<-read.csv("Everolimus_Results_35.csv")
file36<-read.csv("Everolimus_Results_36.csv")
file37<-read.csv("Everolimus_Results_37.csv")
file38<-read.csv("Everolimus_Results_38.csv")
file39<-read.csv("Everolimus_Results_39.csv")
file40<-read.csv("Everolimus_Results_40.csv")
file41<-read.csv("Everolimus_Results_41.csv")
file42<-read.csv("Everolimus_Results_42.csv")
file43<-read.csv("Everolimus_Results_43.csv")
file44<-read.csv("Everolimus_Results_44.csv")
file45<-read.csv("Everolimus_Results_45.csv")
file46<-read.csv("Everolimus_Results_46.csv")
file47<-read.csv("Everolimus_Results_47.csv")
file48<-read.csv("Everolimus_Results_48.csv")
file49<-read.csv("Everolimus_Results_49.csv")
file50<-read.csv("Everolimus_Results_50.csv")
file51<-read.csv("Everolimus_Results_51.csv")
file52<-read.csv("Everolimus_Results_52.csv")
file53<-read.csv("Everolimus_Results_53.csv")
file54<-read.csv("Everolimus_Results_54.csv")
file55<-read.csv("Everolimus_Results_55.csv")
file56<-read.csv("Everolimus_Results_56.csv")
file57<-read.csv("Everolimus_Results_57.csv")
file58<-read.csv("Everolimus_Results_58.csv")
file59<-read.csv("Everolimus_Results_59.csv")
file60<-read.csv("Everolimus_Results_60.csv")
file61<-read.csv("Everolimus_Results_61.csv")
file62<-read.csv("Everolimus_Results_62.csv")
file63<-read.csv("Everolimus_Results_63.csv")
file64<-read.csv("Everolimus_Results_64.csv")
file65<-read.csv("Everolimus_Results_65.csv")
file66<-read.csv("Everolimus_Results_66.csv")
file67<-read.csv("Everolimus_Results_67.csv")
file68<-read.csv("Everolimus_Results_68.csv")
file69<-read.csv("Everolimus_Results_69.csv")
file70<-read.csv("Everolimus_Results_70.csv")
file71<-read.csv("Everolimus_Results_71.csv")
file72<-read.csv("Everolimus_Results_72.csv")
file73<-read.csv("Everolimus_Results_73.csv")
file74<-read.csv("Everolimus_Results_74.csv")
file75<-read.csv("Everolimus_Results_75.csv")
file76<-read.csv("Everolimus_Results_76.csv")
file77<-read.csv("Everolimus_Results_77.csv")
file78<-read.csv("Everolimus_Results_78.csv")
file79<-read.csv("Everolimus_Results_79.csv")
file80<-read.csv("Everolimus_Results_80.csv")
file81<-read.csv("Everolimus_Results_81.csv")
file82<-read.csv("Everolimus_Results_82.csv")
file83<-read.csv("Everolimus_Results_83.csv")
file84<-read.csv("Everolimus_Results_84.csv")
file85<-read.csv("Everolimus_Results_85.csv")
file86<-read.csv("Everolimus_Results_86.csv")
file87<-read.csv("Everolimus_Results_87.csv")
file88<-read.csv("Everolimus_Results_88.csv")
file89<-read.csv("Everolimus_Results_89.csv")
file90<-read.csv("Everolimus_Results_90.csv")
file91<-read.csv("Everolimus_Results_91.csv")
file92<-read.csv("Everolimus_Results_92.csv")
file93<-read.csv("Everolimus_Results_93.csv")
file94<-read.csv("Everolimus_Results_94.csv")
file95<-read.csv("Everolimus_Results_95.csv")
file96<-read.csv("Everolimus_Results_96.csv")
file97<-read.csv("Everolimus_Results_97.csv")
file98<-read.csv("Everolimus_Results_98.csv")
file99<-read.csv("Everolimus_Results_99.csv")
file100<-read.csv("Everolimus_Results_100.csv")

all<-merge(file1,file2, by="X")
all<-merge(all,file3, by="X")
all<-merge(all,file4, by="X")
all<-merge(all,file5, by="X")
all<-merge(all,file6, by="X")
all<-merge(all,file7, by="X")
all<-merge(all,file8, by="X")
all<-merge(all,file9, by="X")
all<-merge(all,file10, by="X")
all<-merge(all,file11, by="X")
all<-merge(all,file12, by="X")
all<-merge(all,file13, by="X")
all<-merge(all,file14, by="X")
all<-merge(all,file15, by="X")
all<-merge(all,file16, by="X")
all<-merge(all,file17, by="X")
all<-merge(all,file18, by="X")
all<-merge(all,file19, by="X")
all<-merge(all,file20, by="X")
all<-merge(all,file21, by="X")
all<-merge(all,file22, by="X")
all<-merge(all,file23, by="X")
all<-merge(all,file24, by="X")
all<-merge(all,file25, by="X")
all<-merge(all,file26, by="X")
all<-merge(all,file27, by="X")
all<-merge(all,file28, by="X")
all<-merge(all,file29, by="X")
all<-merge(all,file30, by="X")
all<-merge(all,file31, by="X")
all<-merge(all,file32, by="X")
all<-merge(all,file33, by="X")
all<-merge(all,file34, by="X")
all<-merge(all,file35, by="X")
all<-merge(all,file36, by="X")
all<-merge(all,file37, by="X")
all<-merge(all,file38, by="X")
all<-merge(all,file39, by="X")
all<-merge(all,file40, by="X")
all<-merge(all,file41, by="X")
all<-merge(all,file42, by="X")
all<-merge(all,file43, by="X")
all<-merge(all,file44, by="X")
all<-merge(all,file45, by="X")
all<-merge(all,file46, by="X")
all<-merge(all,file47, by="X")
all<-merge(all,file48, by="X")
all<-merge(all,file49, by="X")
all<-merge(all,file50, by="X")
all<-merge(all,file51, by="X")
all<-merge(all,file52, by="X")
all<-merge(all,file53, by="X")
all<-merge(all,file54, by="X")
all<-merge(all,file55, by="X")
all<-merge(all,file56, by="X")
all<-merge(all,file57, by="X")
all<-merge(all,file58, by="X")
all<-merge(all,file59, by="X")
all<-merge(all,file60, by="X")
all<-merge(all,file61, by="X")
all<-merge(all,file62, by="X")
all<-merge(all,file63, by="X")
all<-merge(all,file64, by="X")
all<-merge(all,file65, by="X")
all<-merge(all,file66, by="X")
all<-merge(all,file67, by="X")
all<-merge(all,file68, by="X")
all<-merge(all,file69, by="X")
all<-merge(all,file70, by="X")
all<-merge(all,file71, by="X")
all<-merge(all,file72, by="X")
all<-merge(all,file73, by="X")
all<-merge(all,file74, by="X")
all<-merge(all,file75, by="X")
all<-merge(all,file76, by="X")
all<-merge(all,file77, by="X")
all<-merge(all,file78, by="X")
all<-merge(all,file79, by="X")
all<-merge(all,file80, by="X")
all<-merge(all,file81, by="X")
all<-merge(all,file82, by="X")
all<-merge(all,file83, by="X")
all<-merge(all,file84, by="X")
all<-merge(all,file85, by="X")
all<-merge(all,file86, by="X")
all<-merge(all,file87, by="X")
all<-merge(all,file88, by="X")
all<-merge(all,file89, by="X")
all<-merge(all,file90, by="X")
all<-merge(all,file91, by="X")
all<-merge(all,file92, by="X")
all<-merge(all,file93, by="X")
all<-merge(all,file94, by="X")
all<-merge(all,file95, by="X")
all<-merge(all,file96, by="X")
all<-merge(all,file97, by="X")
all<-merge(all,file98, by="X")
all<-merge(all,file99, by="X")
all<-merge(all,file100, by="X")
write.csv(all, "Everolimus_results_overall.csv")
